controller.auth.admin.username=eva-submission-ws-admin-user
controller.auth.admin.password=eva-submission-ws-admin-pass

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres_db:5432/metadata_db
spring.datasource.username=metadata_db_user
spring.datasource.password=metadata_db_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=eva_submissions
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

globus.clientId=test-client-id
globus.clientSecret=test-client-secret
globus.refreshToken=test-refresh-token
globus.uploadHttpDomain=http://mock-globus:5000
globus.submission.endpointId=test-submission-endpoint-id
globus.token.endpoint=http://mock-globus:5000/v2/oauth2/token
globus.transfer.base.url=http://mock-globus:5000/v0.10/operation/endpoint

eva.helpdesk.email=eva-helpdesk@ebi.ac.uk
eva.consent.statement=eva-consent-statement
eva.email.server=mailhog
eva.email.port=1025

lsri.clientId=lsri-client-id
lsri.clientSecret=lsri-client-secret
lsri.userinfo.url=lsri-userinfo-url
lsri.token.url=lsri-token-url

webin.userinfo.url=https://wwwdev.ebi.ac.uk/ena/submit/webin/auth/admin/submission-account

callhome.schema.url=https://raw.githubusercontent.com/EBIvariation/eva-sub-cli/main/eva_sub_cli/etc/call_home_payload_schema.json
eva.submission.account=eva_webin

server.servlet.context-path=/eva/webservices/submission-ws

management.metrics.binders.jvm.enabled=false

spring.cache.type=simple