controller.auth.admin.username=contig_alias_admin_user
controller.auth.admin.password=contig_alias_admin_pass

spring.datasource.url=jdbc:postgresql://postgres_db:5432/contig_alias
spring.datasource.username=contig_alias_user
spring.datasource.password=contig_alias_pass
spring.jpa.hibernate.ddl-auto=update

ftp.proxy.host=null
ftp.proxy.port=0

config.scaffolds.enabled=true
