
services:
  eva_submission:
    image: eva_submission_test
    build:
      # context to where the maven file is located
      context: .
      dockerfile: eva_submission/Dockerfile
      args:
        SOURCE_GITHUB_REPOSITORY: $SOURCE_GITHUB_REPOSITORY
        SOURCE_GITHUB_REF: $SOURCE_GITHUB_REF
        SOURCE_GITHUB_SHA: $SOURCE_GITHUB_SHA
    container_name: eva_submission_test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres_db:
        condition: service_healthy
      oracle_db:
        condition: service_healthy
      mongo_db:
        condition: service_healthy
      eva-submission-ws:
        condition: service_started
      mock-ws:
        condition: service_started
    networks:
      - eva_network

  eva-submission-ws:
    image: eva_submission_ws_test
    build:
      context: ./eva_submission_ws
      dockerfile: Dockerfile
    container_name: eva_submission_ws_test
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - eva_network

  contig-alias:
    image: contig_alias_ws_test
    build:
      # context to where the maven file is located
      context: .
      dockerfile: contig_alias_ws/Dockerfile
    container_name: contig_alias_ws_test
    restart: always
    ports:
      - 8081:8080
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - eva_network

  postgres_db:
    image: postgres_db_test
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    container_name: postgres_db_test
    restart: always
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=root_pass
    ports:
      - 5432:5432
    networks:
      - eva_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root_user" ]
      interval: 5s
      timeout: 30s
      retries: 5

  oracle_db:
    image: oracle_db_test
    build:
      context: ./oracle_db
      dockerfile: Dockerfile
    container_name: oracle_db_test
    restart: always
    environment:
      ORACLE_PASSWORD: oracle_pass
    ports:
      - 1521:1521
    networks:
      - eva_network
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/oracle_init_complete"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 180s

  mongo_db:
    image: mongo_db_test
    build:
      context: ./mongo_db
      dockerfile: Dockerfile
    container_name: mongo_db_test
    restart: always
    ports:
      - 27017:27017
    networks:
      - eva_network
    healthcheck:
      test:
        [
          "CMD", "mongosh", "--eval", "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  mock-ws:
    image: mock_ws_test
    build:
      context: ./mock_ws
      dockerfile: Dockerfile
    container_name: mock_ws_test
    restart: always
    ports:
      - 8082:8080
    networks:
      - eva_network

networks:
  eva_network:
    name: eva_network