
services:
  eva_submission:
    image: eva_submission_test
    build:
      # context to where the maven file is located
      context: .
      dockerfile: eva_submission/Dockerfile
      args:
        SOURCE_GITHUB_REPOSITORY: $SOURCE_GITHUB_REPOSITORY
        SOURCE_GITHUB_REF: $SOURCE_GITHUB_REF
        SOURCE_GITHUB_SHA: $SOURCE_GITHUB_SHA
    container_name: eva_submission_test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres_db:
        condition: service_healthy
      eva-submission-ws:
        condition: service_started
    networks:
      - eva_network

  eva-submission-ws:
    image: eva_submission_ws_test
    build:
      context: ./eva_submission_ws
      dockerfile: Dockerfile
    container_name: eva_submission_ws_test
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - eva_network

  contig-alias:
    image: contig-alias
    build:
      # context to where the maven file is located
      context: .
      dockerfile: contig_alias_ws/Dockerfile
    container_name: contig_alias_ws_test
    restart: always
    ports:
      - 8081:8080
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - eva_network

  postgres_db:
    image: postgres_db_test
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    container_name: postgres_db_test
    restart: always
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=root_pass
    ports:
      - 5432:5432
    networks:
      - eva_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  eva_network:
    name: eva_network