version: "3.8"

services:
  eva_sub_cli:
    image: eva_sub_cli_test
    build:
      context: ./eva_sub_cli
      dockerfile: Dockerfile
    container_name: eva_sub_cli_test
    environment:
      SUBMISSION_WS_URL: http://eva-submission-ws:8080/eva/webservices/submission-ws/v1/
      GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      GITHUB_REF: $GITHUB_REF
      GITHUB_SHA: $GITHUB_SHA
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - eva-submission-ws
    networks:
      - eva_network

  eva-submission-ws:
    image: eva_submission_ws_test
    build:
      context: ./eva_submission_ws
      dockerfile: Dockerfile
    container_name: eva_submission_ws_test
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
      - mock_globus
      - mailhog
    networks:
      - eva_network

  postgres_db:
    image: postgres_db_test
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    container_name: postgres_db_test
    restart: always
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=root_pass
    ports:
      - 5432:5432
    networks:
      - eva_network

  mock_globus:
    image: mock_globus_test
    build:
      context: ./mock_globus
      dockerfile: Dockerfile
    container_name: mock_globus_test
    restart: always
    ports:
      - 5000:5000
    networks:
      - eva_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - eva_network

networks:
  eva_network:
    name: eva_network