-- Connect to FREEPDB1
CONNECT sys/oracle_pass@//localhost:1521/FREEPDB1 as sysdba

-- Create the main user
CREATE USER oracle_user IDENTIFIED BY oracle_pass;
GRANT CONNECT, RESOURCE, CREATE SESSION, UNLIMITED TABLESPACE TO oracle_user;

-- Create user era
CREATE USER era IDENTIFIED BY oracle_pass;
GRANT CONNECT, RESOURCE, CREATE SESSION, UNLIMITED TABLESPACE TO era;

-- Create schema ERA
ALTER SESSION SET CURRENT_SCHEMA = era;

-- Create PROJECT table
CREATE TABLE era.PROJECT (
    PROJECT_ID VARCHAR2(15) PRIMARY KEY,
    CENTER_NAME VARCHAR2(500),
    PROJECT_ALIAS VARCHAR2(500),
    FIRST_CREATED TIMESTAMP,
    PROJECT_TITLE VARCHAR2(4000),
    TAX_ID NUMBER(10),
    SCIENTIFIC_NAME VARCHAR2(255),
    COMMON_NAME VARCHAR2(255),
    PROJECT_XML XMLTYPE
);

-- Create STUDY table
CREATE TABLE era.STUDY (
    STUDY_ID VARCHAR2(15) PRIMARY KEY,
    PROJECT_ID VARCHAR2(15),
    SUBMISSION_ID VARCHAR2(15),
    STUDY_TYPE VARCHAR2(100),
    STUDY_XML XMLTYPE
);

CREATE TABLE era.ENA_LINK (
    FROM_ID VARCHAR2(15) NOT NULL,
    TO_ID VARCHAR2(15) NOT NULL,
    TO_LINK_TYPE_ID NUMBER(10) NOT NULL,
    LINK_ROLE_ID NUMBER(10) NOT NULL
);

CREATE TABLE era.SUBMISSION (
    SUBMISSION_ID   VARCHAR2(15) PRIMARY KEY,
    SUBMISSION_XML  XMLTYPE,
    LAST_UPDATED    TIMESTAMP
);

CREATE TABLE era.ANALYSIS (
    ANALYSIS_ID           VARCHAR2(15) PRIMARY KEY,
    SUBMISSION_ID         VARCHAR2(15),
    ANALYSIS_TITLE        VARCHAR2(4000),
    ANALYSIS_ALIAS        VARCHAR2(500),
    ANALYSIS_TYPE         VARCHAR2(100),
    CENTER_NAME           VARCHAR2(500),
    FIRST_CREATED         TIMESTAMP,
    ANALYSIS_XML          XMLTYPE,
    SUBMISSION_ACCOUNT_ID VARCHAR2(100),
    STATUS_ID             NUMBER(10),
    STUDY_ID              VARCHAR2(15),
    BIOPROJECT_ID         VARCHAR2(15)
);

CREATE TABLE era.WEBIN_FILE (
    SUBMISSION_FILE_ID VARCHAR2(50) PRIMARY KEY,
    DATA_FILE_OWNER_ID VARCHAR2(50) NOT NULL,
    DATA_FILE_PATH VARCHAR2(500) NOT NULL,
    CHECKSUM VARCHAR2(32),
    DATA_FILE_FORMAT VARCHAR2(50),
    BYTES NUMBER(20)
);

CREATE TABLE era.ANALYSIS_SUBMISSION_FILE (
    ANALYSIS_ID VARCHAR2(50) NOT NULL
);

CREATE TABLE era.SAMPLE (
    SAMPLE_ID VARCHAR2(50) PRIMARY KEY,
    BIOSAMPLE_ID VARCHAR2(50)
);

CREATE TABLE era.ANALYSIS_SAMPLE (
    ANALYSIS_ID VARCHAR2(50) NOT NULL,
    SAMPLE_ID VARCHAR2(50) NOT NULL
);

-- Grant privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON era.PROJECT TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.STUDY TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.ENA_LINK TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.SUBMISSION TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.ANALYSIS TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.WEBIN_FILE TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.ANALYSIS_SUBMISSION_FILE TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.SAMPLE TO oracle_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON era.ANALYSIS_SAMPLE TO oracle_user;

COMMIT;