spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres_db:5432/metadata_db
spring.datasource.username=metadata_db_user
spring.datasource.password=metadata_db_pass
spring.jpa.hibernate.ddl-auto=update

controller.auth.admin.username=contig_alias_admin_user
controller.auth.admin.password=contig_alias_admin_pass

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.metrics.binders.jvm.enabled=false

server.servlet.context-path=/eva/webservices/count-stats

management.endpoints.web.exposure.include=info,health
management.info.git.mode=simple